#!/bin/bash

set -e

# Build script for ELK stack

# Update our ubuntu images.
docker pull ubuntu

docker build -t ubuntu-java8 ./ubuntu-java8
docker build -t ubuntu-elasticsearch ./ubuntu-elasticsearch
docker build -t ubuntu-kibana ./ubuntu-kibana
docker build -t ubuntu-logstash ./ubuntu-logstash