#!/bin/bash

set -e

# Build script for ELK stack

repo=mikes1988

# Update our ubuntu images.
docker pull ubuntu

for t in ubuntu-java8 ubuntu-elasticsearch ubuntu-kibana ubuntu-logstash; do
  docker build -t $repo/$t ./$t
  docker push $repo/$t
done

